- name: "Add the group {{ item }}"
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop:
    - avermeer
    - pozar
    - matt

- name: "Add the user {{ item }}"
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: "{{ item }},sudo"
  loop:
    - avermeer
    - pozar
    - matt

- name: Create .ssh folder
  ansible.builtin.file:
    path: "/home/{{ item }}/.ssh"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0700
  loop:
    - avermeer
    - pozar
    - matt

- name: Upload SSH key
  ansible.builtin.copy:
    src: "files/{{ item }}.pub"
    dest: "/home/{{ item }}/.ssh/authorized_keys"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0600
  loop:
    - avermeer
    - pozar
    - matt

- name: Add sudoers file
  ansible.builtin.template:
    src: "templates/sudoers.j2"
    dest: "/etc/sudoers.d/{{ item }}"
    owner: "root"
    group: "root"
    mode: 0440
  loop:
    - avermeer
    - pozar
    - matt